name: flutter_bitshares
description: Bitshares wallet writen in Flutter.
author: Pavel Kozlovskiy <pavel2033@gmail.com>
homepage: https://github.com/pkozlovskiy/flutter_bitshares

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  graphened:
    path: ./graphened

  logging: ^0.11.3+2
  meta:
  equatable: ^0.2.3
  built_value: ^6.1.4
  provider: 2.0.1
  rxdart: 0.22.0
  web_socket_channel: ^1.0.12
  connectivity: ^0.4.3+2
  path_provider:
  shared_preferences: ^0.5.2
  flutter_svg: ^0.12.3
  moor_flutter:

dev_dependencies:
  build_runner: ^1.1.3
  built_value_generator: ^6.1.4
  moor_generator: 

  test: 
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/bitshares_logo.svg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
